# Freenom账户 Freenom Account

FREENOM_USERNAME=yangmimami333@gmail.com

# Freenom密码 Freenom password

FREENOM_PASSWORD=172839mc

#多账户支持 Support for multiple accounts

MULTIPLE_ACCOUNTS="

end 账户配置

######

##########

#######

################ 通知邮件配置 Email config

# 机器人邮箱账户 Email of robot

MAIL_USERNAME=2907577140@qq.com

#机器人邮箱密码

(Gmail填密码，QQ邮箱或163邮箱填授权码）

Password of the robot email

MAIL_PASSWORD=nbxbiqbgozhudhbb

#用于接收通知的邮箱 Email address used to receive notifications

TO=yangmimami333@gmail.com

#是否启用邮件推送功能 true:启用 false:不启用 Whether to enable email push features true:enable

d false: not enabled

MAIL_ENABLE=true

end 通知邮件配置

######################

#########################

####################### Telegram bot

#可选配置，通过 Telegram bot 发送通知消息 This is an optional configuration to send notification messages via Telegram bot

#你的chat_id,通过发送"/start"给@userinfobot可以获取自己的id Your chat_id,you can get your own

d by sending "/start" to @userinfobot

TELEGRAM_CHAT_ID= No

# 你的Telegram bot的 token Token for your Telegram bot

TELEGRAM_BOT_TOKEN= No

#是否启用 Telegram Bot 功能 true: 启用 false: 不启用 Whether to enable Telegram Bot features true: enabled false: not enabled

TELEGRAM_BOT_ENABLE=false

end Telegram bot

######################

#######################

# 通知频率 0:仅当有续期操作的时候 1:每次执行 Notification frequency 0: Only when there is a rene wal operation 1: Each execution

NOTICE_FREQ=1

# 在 Github Actions 上运行 Run on github actions

ON_GITHUB_ACTIONS=false

#是否验证服务器证书 Whether to verify server certificate

VERIFY_SSL=false

#是否开启 Debug 模式 Whether to enable debug mode

DEBUG=false

i

